# Generated by Django 5.1.3 on 2024-11-28 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('listings', '0004_alter_listing_bedrooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalapplication',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='rentalapplication',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
