# Generated by Django 5.1.3 on 2024-11-18 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('bedrooms', models.PositiveIntegerField(null=True)),
                ('bathrooms', models.PositiveIntegerField(null=True)),
                ('kitchens', models.PositiveIntegerField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pets', models.BooleanField(default=False)),
                ('smokes', models.BooleanField(default=False)),
                ('drinks', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
