# Generated by Django 5.1.3 on 2024-11-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Studio', 'Studio'), ('Basement', 'Basement'), ('Room', 'Room')], max_length=10, null=True),
        ),
    ]
