# Generated by Django 5.1.3 on 2024-11-29 00:49

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_userprofile_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', null=True, upload_to=profiles.models.generate_unique_filename),
        ),
    ]
