name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     # - name: Run tests
        #run: |
          #python manage.py test

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host gcp-vm" >> ~/.ssh/config
          echo "  HostName 35.224.56.180" >> ~/.ssh/config   # Use actual IP address here
          echo "  User jjjchen52" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          ssh-keyscan -H 35.224.56.180 >> ~/.ssh/known_hosts

      - name: Deploy React app
        run: |
          ssh -T gcp-vm << 'EOF'
            cd /home/jjjchen52/project-unirentals/frontend
            git pull origin main
            npm install
            npm run build 
            pm2 restart "react-app"
          EOF


      - name: Deploy Application
        run: |
          ssh -T gcp-vm << 'EOF'
            cd /home/jjjchen52/project-unirentals
            git pull origin main
            source /venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
            sudo systemctl reload nginx
          EOF
