name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host gcp-vm" >> ~/.ssh/config
        echo "  HostName your-vm-ip" >> ~/.ssh/config
        echo "  User your-username" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config

    # Step 3: Deploy to GCP VM
    - name: Deploy Application
      run: |
        ssh gcp-vm << 'EOF'
          cd /home/jjjchen52/project-unirentals/
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
        EOF
